"""initial schema

Revision ID: 82d35e3c78ec
Revises: 
Create Date: 2026-08-05 16:21:59.814635
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types  # custom ExactNumeric type referenced below


# revision identifiers, used by Alembic.
revision: str = '82d35e3c78ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('platform_id')
    )
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platforms_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('fee_rules',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price_band_min', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('price_band_max', app.db.types.ExactNumeric(precision=12, scale=2), nullable=True),
    sa.Column('commission_pct', app.db.types.ExactNumeric(precision=5, scale=2), nullable=False),
    sa.Column('fixed_fee', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_slab_weight_g', sa.Integer(), nullable=False),
    sa.Column('shipping_fee', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_gateway_pct', app.db.types.ExactNumeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_pct', app.db.types.ExactNumeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('date_accessed', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.platform_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    with op.batch_alter_table('fee_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_rules_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_rules_effective_from'), ['effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_rules_platform_id'), ['platform_id'], unique=False)

    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('cost_price', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('weight_g', sa.Integer(), nullable=False),
    sa.Column('length_cm', app.db.types.ExactNumeric(precision=6, scale=2), nullable=True),
    sa.Column('width_cm', app.db.types.ExactNumeric(precision=6, scale=2), nullable=True),
    sa.Column('height_cm', app.db.types.ExactNumeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_user_id'), ['user_id'], unique=False)

    op.create_table('rto_rates',
    sa.Column('rto_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('rto_rate_pct', app.db.types.ExactNumeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_rto_cost', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.platform_id'], ),
    sa.PrimaryKeyConstraint('rto_id')
    )
    with op.batch_alter_table('rto_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rto_rates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_rto_rates_effective_from'), ['effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_rto_rates_platform_id'), ['platform_id'], unique=False)

    op.create_table('comparisons',
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('gross_revenue', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_amount', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('fixed_fee_amount', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_amount', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('gateway_amount', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_amount', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('tcs_amount', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('rto_adjusted_cost', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('net_payout', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('profit', app.db.types.ExactNumeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_pct', app.db.types.ExactNumeric(precision=5, scale=2), nullable=False),
    sa.Column('breakeven_price', app.db.types.ExactNumeric(precision=12, scale=2), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.platform_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['fee_rules.rule_id'], ),
    sa.PrimaryKeyConstraint('comparison_id')
    )
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comparisons_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparisons_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparisons_rule_id'), ['rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparisons_rule_id'))
        batch_op.drop_index(batch_op.f('ix_comparisons_product_id'))
        batch_op.drop_index(batch_op.f('ix_comparisons_platform_id'))

    op.drop_table('comparisons')
    with op.batch_alter_table('rto_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rto_rates_platform_id'))
        batch_op.drop_index(batch_op.f('ix_rto_rates_effective_from'))
        batch_op.drop_index(batch_op.f('ix_rto_rates_category'))

    op.drop_table('rto_rates')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_user_id'))
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    with op.batch_alter_table('fee_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_rules_platform_id'))
        batch_op.drop_index(batch_op.f('ix_fee_rules_effective_from'))
        batch_op.drop_index(batch_op.f('ix_fee_rules_category'))

    op.drop_table('fee_rules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platforms_name'))

    op.drop_table('platforms')
    # ### end Alembic commands ###
